export { Hero } from './Hero'
export { Services } from './Services'
export { WhyUs } from './WhyUs'
export { HowItWorks } from './HowItWorks'
export { Pricing } from './Pricing'
export { Testimonials } from './Testimonials'
export { About } from './About'
export { Contact } from './Contact'
